services:
  tilqazyna-kz-website:
    build:
      context: .
      dockerfile: ./sites/tilqazyna.kz/Dockerfile
    container_name: tilqazyna-app
    working_dir: /var/www/html/sites/tilqazyna.kz
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8080"
    command: >
      sh -lc "
      [ -f .env ] || { [ -f .env.example ] && cp .env.example .env || printf 'APP_ENV=local\nAPP_DEBUG=true\nAPP_KEY=\nAPP_URL=http://localhost:8080\nDB_CONNECTION=sqlite\nDB_DATABASE=/var/www/html/sites/tilqazyna.kz/database/database.sqlite\n' > .env; };
      mkdir -p database && touch database/database.sqlite;
      composer install --no-dev --no-interaction --prefer-dist;
      php artisan key:generate --force || true;
      (npm ci || npm install);
      npm run build;
      php artisan serve --host 0.0.0.0 --port 8080
      "
    networks:
      - tilqazyna

networks:
  tilqazyna:
    driver: bridge

volumes:
  # Placeholder for future persistent volumes if needed
  ignore:
    driver: local
