services:
  tilqazyna-kz-website:
    build:
      context: .
      dockerfile: ./sites/tilqazyna.kz/Dockerfile
    container_name: tilqazyna-app
    working_dir: /var/www/html/sites/tilqazyna.kz
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8080"
    environment:
      # Ensures Laravel has an APP_KEY at runtime without custom entrypoint
      # If .env already has APP_KEY, Laravel will ignore this env var.
      APP_KEY: base64:0000000000000000000000000000000000000000000=
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/sites/tilqazyna.kz/database/database.sqlite
    command: sh -lc "[ -f .env ] || cp .env.example .env || true; touch database/database.sqlite; composer install --no-dev --no-interaction --prefer-dist; php artisan key:generate --force || true; php artisan migrate --force || true; php artisan serve --host 0.0.0.0 --port 8080"
    networks:
      - tilqazyna

networks:
  tilqazyna:
    driver: bridge

volumes:
  # Placeholder for future persistent volumes if needed
  ignore:
    driver: local
