services:
  tilqazyna-kz-website:
    build:
      context: .
      dockerfile: ./sites/tilqazyna.kz/Dockerfile
    container_name: tilqazyna-app
    working_dir: /var/www/html/sites/tilqazyna.kz
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8080"
    environment:
      APP_NAME: Tilqazyna
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: https://tilqazyna.kz
      APP_KEY: base64:wl7TtjqbZp9K0W/GPzs8T8aEp0d7s6F6rcPNK7g/csA=
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/sites/tilqazyna.kz/database/database.sqlite
      SESSION_DRIVER: database
      QUEUE_CONNECTION: database
      VITE_APP_NAME: Tilqazyna
    command: >
      sh -lc "
      mkdir -p database && touch database/database.sqlite;
      composer install --no-dev --no-interaction --prefer-dist;
      (npm ci || npm install);
      npm run build;
      php artisan serve --host 0.0.0.0 --port 8080
      "
    networks:
      - tilqazyna

networks:
  tilqazyna:
    driver: bridge

volumes:
  # Placeholder for future persistent volumes if needed
  ignore:
    driver: local
