version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tilqazyna-php
    volumes:
      - ./:/app:delegated
      - ./docker/php/legacy.ini:/usr/local/etc/php/conf.d/zz-legacy.ini:ro
      - assets_frontend:/app/frontend/web/assets
      - assets_backend:/app/backend/web/assets
      - runtime_frontend:/app/frontend/runtime
      - runtime_backend:/app/backend/runtime
    cap_add:
      - NET_ADMIN
    environment:
      PHP_MEMORY_LIMIT: 512M
    networks:
      - legacy

  nginx:
    image: nginx:1.25-alpine
    container_name: tilqazyna-nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./:/app:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - assets_frontend:/app/frontend/web/assets
      - assets_backend:/app/backend/web/assets
    networks:
      - legacy

  mysql:
    image: mysql:5.7
    container_name: tilqazyna-mysql
    command: ["mysqld", "--character-set-server=utf8", "--collation-server=utf8_general_ci"]
    environment:
      MYSQL_ROOT_PASSWORD: xnx63n
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: tilqazyna
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
    networks:
      - legacy

  mysql-provision:
    image: mysql:5.7
    container_name: tilqazyna-mysql-provision
    depends_on:
      - mysql
    entrypoint: ["bash", "-lc", "until mysql -hmysql -uroot -p'xnx63n' -e 'SELECT 1' >/dev/null 2>&1; do sleep 1; done; mysql -hmysql -uroot -p'xnx63n' < /provision/create-users.sql"]
    volumes:
      - ./docker/mysql/provision:/provision:ro
    networks:
      - legacy

volumes:
  db_data:
  assets_frontend:
  assets_backend:
  runtime_frontend:
  runtime_backend:

networks:
  legacy:
    driver: bridge


