<?php
namespace frontend\models;

use common\models\User;
use yii\base\Model;
use Yii;

/**
 * Signup form
 */
class SignupForm extends Model
{
    public $username;
    public $lastname;
    public $password;
    //public $repassword;
    public $avatar;
    public $background;
    public $city;
    public $birthday;
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [

            //['username', 'unique', 'targetClass' => '\common\models\User', 'message' => 'This username has already been taken.'],
            ['username', 'string'],
            ['lastname', 'string'],


            ['password', 'required','message' => 'Толтырыңыз!'],
            ['repassword', 'required','message' => 'Толтырыңыз!'],
            ['repassword', 'compare', 'compareAttribute' => 'password','message' => 'Кілт сөздер сәйкес емес!'],
        ];
    }
    public function scenarios()
    {
        return parent::scenarios(); // TODO: Change the autogenerated stub
    }

    /**
     * Signs user up.
     *
     * @return User|null the saved model or null if saving fails
     */
    public function signup()
    {
        if ($this->validate()) {
            $user = new User();
            $user->username = $this->username;
            $user->lastname = $this->lastname;
            $user->email = $this->email;
            $user->link_role = 1;
            $user->setPassword($this->password);
            $user->generateAuthKey();
            if ($user->save()) {
                return $user;
            }
        }

        return null;
    }
    public function attributeLabels()
    {
        return [
            'username' => 'Имя',
            'password' => 'Пароль',
            'repassword' => 'Повторите пароль',
        ];
    }
}
